### ISSUE TITLE
Passing SVectors to MDBM_Problem

### ISSUE THREAD

**Issue by BeastyBlacksmith** [bachrathyd/MDBM.jl#15]
What is the reason that you can't allow `AbstractArays` [here](https://github.com/bachrathyd/MDBM.jl/blob/0d88f374c2e21cbf7a45781fd965e09cb7a5cc9d/src/MDBM_types.jl#L145)?

I naively expected it to work with `StaticArrays`.

**Comment by bachrathyd** [comment]
Your question is not clear for me.
Did you try to pass a StaticArryas as an 'axis' parameter?
Did you try to use a single variable problem?

Note, that this method is basically designed for multi-variable problem, so variable axes must be provided in a Vector. Even if a single-variable problem is used, then that single axis should be passed in a vector form. 

Try to use this form:
```julia
mymdbm=MDBM_Problem((x)->x^2-2,[-3.0:3.0])
solve!(mymdbm,5)
println(getinterpolatedsolution(mymdbm))
```

**Comment by BeastyBlacksmith** [comment]
my code was more like
```julia
a = Axis([-3,-2,-1,0,1, 2, 3])
b = Axis([-3,-2,-1,0,1, 2, 3])
ax = @SVector [a,b]
mymdbm=MDBM_Problem((x)->x^2-2,ax)
solve!(mymdbm,5)
println(getinterpolatedsolution(mymdbm))
```

**Comment by bachrathyd** [comment]
Thank your for the comment! I did not considered this type of calling.
You are right,  `Vector` is updated to  `AbstractVector` and it solved the problem.
See the [commit](https://github.com/bachrathyd/MDBM.jl/commit/b8fd75408770babd1419267053e12cedbdcf2015)
However, this type of calling will not effect any performance, because the axes is used in a different format (struct), so there is no need to use this form
```julia
ax = @SVector [a,b]
```
it is sufficient to use:
```julia
ax = [a,b]
```
